namespace DebugMenu.ExampleProducerClient;

public class FakeLogGenerator {
    static string[] _messages = new string[] {
        "Missing texture for object \"PlayerCharacter.\" Using default texture.",
        "NullReferenceException - Attempted to access an object that is null.",
        "Frame rate below 30 fps. Consider optimizing performance.",
        "Out of memory. Failed to load asset bundle.",
        "Collider overlap detected between Player and Enemy.",
        "Physics.Raycast hit an object with no collider.",
        "Animation event not found on GameObject \"Player.\"",
        "Unable to find path for NPC navigation.",
        "Shader compilation error - Shader \"EnemyShader\" failed to compile.",
        "Audio clip not found for background music.",
        "Player inventory is full. Item dropped on the ground.",
        "Network connection lost. Disconnected from server.",
        "Camera clipping through terrain. Adjust camera settings.",
        "Player respawn failed. Spawn point is obstructed.",
        "Particle system \"Explosion\" not found on GameObject \"ExplosiveBarrel.\"",
        "UI element \"HealthBar\" not assigned in Inspector.",
        "Player movement input is inconsistent. Check input settings.",
        "Database connection error. Unable to save game progress.",
        "Light intensity exceeds recommended limit. Adjust lighting settings.",
        "Failed to load scene \"Level3.\" Scene not found.",
        "Player leveled up!",
        "New high score achieved.",
        "Item picked up: Sword of Destiny.",
        "Ammo refilled.",
        "Player entered a new area: Forest of Shadows.",
        "Achievement unlocked: \"Master Explorer.\"",
        "Quest completed: \"Rescue the Princess.\"",
        "Game over. Try again?",
        "Player gained 50 experience points.",
        "Boss defeated: Dragon of Doom.",
        "Weapon upgraded to level 3.",
        "Player fell into a pit and lost a life.",
        "Quest updated: \"Find the hidden treasure.\"",
        "Player obtained a key.",
        "Health critical! Use a potion.",
        "Multiplayer match started.",
        "Player reached checkpoint.",
        "Victory! Team Blue wins.",
        "Player defeated by Boss.",
        "New character unlocked: Ninja Assassin.",
        "Ammo depleted. Reload!",
        "Player crafted a new item: Iron Armor.",
        "Player discovered a secret passage.",
        "Level up! You are now level 10.",
        "Player completed a puzzle.",
        "Mission failed. Retry?",
        "Player collected 100 gold coins.",
        "Inventory full. Drop an item.",
        "New quest available: \"Save the Village.\"",
        "Time's up! You failed the challenge.",
        "Player found a hidden chest.",
        "Player joined the Red Team.",
        "Player earned a new badge: Explorer.",
        "Game paused.",
        "Player entered a combat stance.",
        "Player activated a teleporter.",
        "Player's shield blocked an attack.",
        "Game loading. Please wait.",
        "Player unlocked a new skill: Fireball.",
        "Player discovered a rare item: Magic Ring.",
        "Player used a special ability: Invisibility.",
        "Boss health: 10%",
        "Player completed a side quest.",
        "New game update available. Update now?",
        "Player defeated the final boss!",
        "Player captured the flag.",
        "Player upgraded their ship's engines.",
        "Player unlocked a secret character skin.",
        "Player cast a healing spell.",
        "Player triggered a trap.",
        "Player purchased a new weapon: Laser Gun.",
        "Quest failed: \"Find the Lost Amulet.\"",
        "Player received a message from an NPC.",
        "Player activated a time warp.",
        "Player reached a new high score.",
        "Player found a treasure map.",
        "Player crafted a health potion.",
        "Player joined a guild: Knights of Valor.",
        "Player initiated a sneak attack.",
        "Player completed the tutorial.",
        "Player's spaceship was destroyed.",
        "Player solved a riddle.",
        "Player encountered a mysterious stranger.",
        "Player unlocked a new level.",
        "Player defeated a horde of zombies.",
        "Player acquired a new pet: Baby Dragon.",
        "Player completed a wave of enemies.",
        "Player initiated a trade with another player.",
        "Player received a gift from a friend.",
        "Player captured an enemy flag.",
        "Player activated a warp gate.",
        "Player discovered an ancient artifact.",
        "Player reached a new achievement milestone.",
        "Player purchased a house in the village.",
        "Player initiated a boss battle.",
        "Player found a secret weapon cache.",
        "Level completed successfully.",
        "Health potion consumed.",
        "Player took damage from enemy.",
        "Game saved successfully."
    };

    private static string[] _stackTraces = new string[] {
        "Assets/Scripts/GameManager.cs(47): NullReferenceException: Object reference not set to an instance of an object.\n\tat GameManager.Start () (at Assets/Scripts/GameManager.cs:47)\n\tat UnityEngine.MonoBehaviour.InvokeMethodOrCoroutineChecked (System.Object method, System.Object parameters, System.String name)",
        "Assets/Scripts/PlayerController.cs(123): IndexOutOfRangeException: Array index is out of range.\n\tat PlayerController.Update () (at Assets/Scripts/PlayerController.cs:123)\n\tat UnityEngine.MonoBehaviour.InvokeMethodOrCoroutineChecked (System.Object method, System.Object parameters, System.String name)",
        "Assets/Scripts/EnemyAI.cs(76): FileNotFoundException: Could not find file 'EnemyConfig.json'.\n\tat EnemyAI.LoadConfig () (at Assets/Scripts/EnemyAI.cs:76)\n\tat UnityEngine.MonoBehaviour.InvokeMethodOrCoroutineChecked (System.Object method, System.Object parameters, System.String name)",
        "Assets/Scripts/GameManager.cs(135): UnauthorizedAccessException: Access to the path 'SaveData/PlayerData.dat' is denied.\n\tat GameManager.SaveGame () (at Assets/Scripts/GameManager.cs:135)\n\tat UnityEngine.MonoBehaviour.InvokeMethodOrCoroutineChecked (System.Object method, System.Object parameters, System.String name)",
        "Assets/Scripts/UIManager.cs(210): InvalidOperationException: Operation is not valid due to the current state of the object.\n\tat UIManager.DisplayMessage () (at Assets/Scripts/UIManager.cs:210)\n\tat UnityEngine.MonoBehaviour.InvokeMethodOrCoroutineChecked (System.Object method, System.Object parameters, System.String name)"
    };

    static readonly Random _random = new Random();

    private static string[] _types = new string[] { "log", "error", "warning", "exception", "assert" };

    public static (string text, string type, string details) Generate() {
        var idx = _random.Next() % _messages.Length;
        var typeIdx = idx >= 20 ? 0 : 1 + _random.Next() % 4;

        return new(
                _messages[idx],
                _types[typeIdx],
                _stackTraces[_random.Next() % _stackTraces.Length])
            ;
    }
}